//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsms.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsms.Resource.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。
        ///システム管理者へ連絡してください。
        ///エラー内容：
        ///{0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0001_E {
            get {
                return ResourceManager.GetString("DME000_0001_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要求されたページへアクセスする権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0002_E {
            get {
                return ResourceManager.GetString("DME000_0002_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0003_E {
            get {
                return ResourceManager.GetString("DME000_0003_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には半角英数記号で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0004_E {
            get {
                return ResourceManager.GetString("DME000_0004_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以下で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0005_E {
            get {
                return ResourceManager.GetString("DME000_0005_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するデータは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0006_I {
            get {
                return ResourceManager.GetString("DME000_0006_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のデータで使用中のため、削除することができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0007_E {
            get {
                return ResourceManager.GetString("DME000_0007_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するデータは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0008_E {
            get {
                return ResourceManager.GetString("DME000_0008_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のユーザにより更新または削除されています。最新の情報を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0009_E {
            get {
                return ResourceManager.GetString("DME000_0009_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0010_I {
            get {
                return ResourceManager.GetString("DME000_0010_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には数値で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0011_E {
            get {
                return ResourceManager.GetString("DME000_0011_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存します。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0012_Q {
            get {
                return ResourceManager.GetString("DME000_0012_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0013_I {
            get {
                return ResourceManager.GetString("DME000_0013_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータを削除します。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0014_Q {
            get {
                return ResourceManager.GetString("DME000_0014_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には半角英数で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0015_E {
            get {
                return ResourceManager.GetString("DME000_0015_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にはメールアドレス形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0016_E {
            get {
                return ResourceManager.GetString("DME000_0016_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一意制約に反しているため、登録できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0017_E {
            get {
                return ResourceManager.GetString("DME000_0017_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のファイル形式は登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0018_E {
            get {
                return ResourceManager.GetString("DME000_0018_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には日時を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0019_E {
            get {
                return ResourceManager.GetString("DME000_0019_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイルがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0020_E {
            get {
                return ResourceManager.GetString("DME000_0020_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルにデータが1件もありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0021_E {
            get {
                return ResourceManager.GetString("DME000_0021_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目の{1}は必須入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0022_E {
            get {
                return ResourceManager.GetString("DME000_0022_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目の{1}は半角英数で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0023_E {
            get {
                return ResourceManager.GetString("DME000_0023_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目の{1}は数値で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0024_E {
            get {
                return ResourceManager.GetString("DME000_0024_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目の{1}は{2}以下で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0025_E {
            get {
                return ResourceManager.GetString("DME000_0025_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目の{1}は存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0026_E {
            get {
                return ResourceManager.GetString("DME000_0026_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下エラーのため、一括登録できませんでした。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0027_E {
            get {
                return ResourceManager.GetString("DME000_0027_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にはかな文字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0028_E {
            get {
                return ResourceManager.GetString("DME000_0028_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には日付を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0029_E {
            get {
                return ResourceManager.GetString("DME000_0029_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には時刻を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0030_E {
            get {
                return ResourceManager.GetString("DME000_0030_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}には半角英字で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME000_0031_E {
            get {
                return ResourceManager.GetString("DME000_0031_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザコード、又は、パスワードが間違っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME001_0001_E {
            get {
                return ResourceManager.GetString("DME001_0001_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたユーザコードが存在しないか、メールアドレスが登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME001_0002_E {
            get {
                return ResourceManager.GetString("DME001_0002_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールを送信しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DME001_0003_I {
            get {
                return ResourceManager.GetString("DME001_0003_I", resourceCulture);
            }
        }
    }
}
